// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: job/job.proto

package job

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TriggerJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int64                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TenantId      int64                  `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerJobRequest) Reset() {
	*x = TriggerJobRequest{}
	mi := &file_job_job_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerJobRequest) ProtoMessage() {}

func (x *TriggerJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_job_job_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerJobRequest.ProtoReflect.Descriptor instead.
func (*TriggerJobRequest) Descriptor() ([]byte, []int) {
	return file_job_job_proto_rawDescGZIP(), []int{0}
}

func (x *TriggerJobRequest) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *TriggerJobRequest) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

type TriggerJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   int64                  `protobuf:"varint,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerJobResponse) Reset() {
	*x = TriggerJobResponse{}
	mi := &file_job_job_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerJobResponse) ProtoMessage() {}

func (x *TriggerJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_job_job_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerJobResponse.ProtoReflect.Descriptor instead.
func (*TriggerJobResponse) Descriptor() ([]byte, []int) {
	return file_job_job_proto_rawDescGZIP(), []int{1}
}

func (x *TriggerJobResponse) GetExecutionId() int64 {
	if x != nil {
		return x.ExecutionId
	}
	return 0
}

type GetJobStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int64                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobStatusRequest) Reset() {
	*x = GetJobStatusRequest{}
	mi := &file_job_job_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobStatusRequest) ProtoMessage() {}

func (x *GetJobStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_job_job_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobStatusRequest.ProtoReflect.Descriptor instead.
func (*GetJobStatusRequest) Descriptor() ([]byte, []int) {
	return file_job_job_proto_rawDescGZIP(), []int{2}
}

func (x *GetJobStatusRequest) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type GetJobStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int64                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	CronExpr      string                 `protobuf:"bytes,4,opt,name=cron_expr,json=cronExpr,proto3" json:"cron_expr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobStatusResponse) Reset() {
	*x = GetJobStatusResponse{}
	mi := &file_job_job_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobStatusResponse) ProtoMessage() {}

func (x *GetJobStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_job_job_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobStatusResponse.ProtoReflect.Descriptor instead.
func (*GetJobStatusResponse) Descriptor() ([]byte, []int) {
	return file_job_job_proto_rawDescGZIP(), []int{3}
}

func (x *GetJobStatusResponse) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *GetJobStatusResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetJobStatusResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetJobStatusResponse) GetCronExpr() string {
	if x != nil {
		return x.CronExpr
	}
	return ""
}

var File_job_job_proto protoreflect.FileDescriptor

const file_job_job_proto_rawDesc = "" +
	"\n" +
	"\rjob/job.proto\x12\x03job\"I\n" +
	"\x11TriggerJobRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x03R\x06taskId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\x03R\btenantId\"7\n" +
	"\x12TriggerJobResponse\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\x03R\vexecutionId\".\n" +
	"\x13GetJobStatusRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x03R\x06taskId\"x\n" +
	"\x14GetJobStatusResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x03R\x06taskId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12\x1b\n" +
	"\tcron_expr\x18\x04 \x01(\tR\bcronExpr2\x90\x01\n" +
	"\n" +
	"JobService\x12=\n" +
	"\n" +
	"TriggerJob\x12\x16.job.TriggerJobRequest\x1a\x17.job.TriggerJobResponse\x12C\n" +
	"\fGetJobStatus\x12\x18.job.GetJobStatusRequest\x1a\x19.job.GetJobStatusResponseB\"Z management-backend/api/proto/jobb\x06proto3"

var (
	file_job_job_proto_rawDescOnce sync.Once
	file_job_job_proto_rawDescData []byte
)

func file_job_job_proto_rawDescGZIP() []byte {
	file_job_job_proto_rawDescOnce.Do(func() {
		file_job_job_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_job_job_proto_rawDesc), len(file_job_job_proto_rawDesc)))
	})
	return file_job_job_proto_rawDescData
}

var file_job_job_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_job_job_proto_goTypes = []any{
	(*TriggerJobRequest)(nil),    // 0: job.TriggerJobRequest
	(*TriggerJobResponse)(nil),   // 1: job.TriggerJobResponse
	(*GetJobStatusRequest)(nil),  // 2: job.GetJobStatusRequest
	(*GetJobStatusResponse)(nil), // 3: job.GetJobStatusResponse
}
var file_job_job_proto_depIdxs = []int32{
	0, // 0: job.JobService.TriggerJob:input_type -> job.TriggerJobRequest
	2, // 1: job.JobService.GetJobStatus:input_type -> job.GetJobStatusRequest
	1, // 2: job.JobService.TriggerJob:output_type -> job.TriggerJobResponse
	3, // 3: job.JobService.GetJobStatus:output_type -> job.GetJobStatusResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_job_job_proto_init() }
func file_job_job_proto_init() {
	if File_job_job_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_job_job_proto_rawDesc), len(file_job_job_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_job_job_proto_goTypes,
		DependencyIndexes: file_job_job_proto_depIdxs,
		MessageInfos:      file_job_job_proto_msgTypes,
	}.Build()
	File_job_job_proto = out.File
	file_job_job_proto_goTypes = nil
	file_job_job_proto_depIdxs = nil
}
