// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: system/menu.proto

package system

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateMenuReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentId      int64                  `protobuf:"varint,1,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	MenuName      string                 `protobuf:"bytes,2,opt,name=menu_name,json=menuName,proto3" json:"menu_name,omitempty"`
	MenuType      int32                  `protobuf:"varint,3,opt,name=menu_type,json=menuType,proto3" json:"menu_type,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Component     string                 `protobuf:"bytes,5,opt,name=component,proto3" json:"component,omitempty"`
	Permission    string                 `protobuf:"bytes,6,opt,name=permission,proto3" json:"permission,omitempty"`
	Icon          string                 `protobuf:"bytes,7,opt,name=icon,proto3" json:"icon,omitempty"`
	Sort          int32                  `protobuf:"varint,8,opt,name=sort,proto3" json:"sort,omitempty"`
	Visible       int32                  `protobuf:"varint,9,opt,name=visible,proto3" json:"visible,omitempty"`
	Status        int32                  `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMenuReq) Reset() {
	*x = CreateMenuReq{}
	mi := &file_system_menu_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMenuReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMenuReq) ProtoMessage() {}

func (x *CreateMenuReq) ProtoReflect() protoreflect.Message {
	mi := &file_system_menu_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMenuReq.ProtoReflect.Descriptor instead.
func (*CreateMenuReq) Descriptor() ([]byte, []int) {
	return file_system_menu_proto_rawDescGZIP(), []int{0}
}

func (x *CreateMenuReq) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *CreateMenuReq) GetMenuName() string {
	if x != nil {
		return x.MenuName
	}
	return ""
}

func (x *CreateMenuReq) GetMenuType() int32 {
	if x != nil {
		return x.MenuType
	}
	return 0
}

func (x *CreateMenuReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CreateMenuReq) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *CreateMenuReq) GetPermission() string {
	if x != nil {
		return x.Permission
	}
	return ""
}

func (x *CreateMenuReq) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *CreateMenuReq) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *CreateMenuReq) GetVisible() int32 {
	if x != nil {
		return x.Visible
	}
	return 0
}

func (x *CreateMenuReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type UpdateMenuReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ParentId      int64                  `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	MenuName      string                 `protobuf:"bytes,3,opt,name=menu_name,json=menuName,proto3" json:"menu_name,omitempty"`
	MenuType      int32                  `protobuf:"varint,4,opt,name=menu_type,json=menuType,proto3" json:"menu_type,omitempty"`
	Path          string                 `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`
	Component     string                 `protobuf:"bytes,6,opt,name=component,proto3" json:"component,omitempty"`
	Permission    string                 `protobuf:"bytes,7,opt,name=permission,proto3" json:"permission,omitempty"`
	Icon          string                 `protobuf:"bytes,8,opt,name=icon,proto3" json:"icon,omitempty"`
	Sort          int32                  `protobuf:"varint,9,opt,name=sort,proto3" json:"sort,omitempty"`
	Visible       int32                  `protobuf:"varint,10,opt,name=visible,proto3" json:"visible,omitempty"`
	Status        int32                  `protobuf:"varint,11,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMenuReq) Reset() {
	*x = UpdateMenuReq{}
	mi := &file_system_menu_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMenuReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMenuReq) ProtoMessage() {}

func (x *UpdateMenuReq) ProtoReflect() protoreflect.Message {
	mi := &file_system_menu_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMenuReq.ProtoReflect.Descriptor instead.
func (*UpdateMenuReq) Descriptor() ([]byte, []int) {
	return file_system_menu_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateMenuReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateMenuReq) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *UpdateMenuReq) GetMenuName() string {
	if x != nil {
		return x.MenuName
	}
	return ""
}

func (x *UpdateMenuReq) GetMenuType() int32 {
	if x != nil {
		return x.MenuType
	}
	return 0
}

func (x *UpdateMenuReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *UpdateMenuReq) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *UpdateMenuReq) GetPermission() string {
	if x != nil {
		return x.Permission
	}
	return ""
}

func (x *UpdateMenuReq) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *UpdateMenuReq) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *UpdateMenuReq) GetVisible() int32 {
	if x != nil {
		return x.Visible
	}
	return 0
}

func (x *UpdateMenuReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type MenuNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ParentId      int64                  `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	MenuName      string                 `protobuf:"bytes,3,opt,name=menu_name,json=menuName,proto3" json:"menu_name,omitempty"`
	MenuType      int32                  `protobuf:"varint,4,opt,name=menu_type,json=menuType,proto3" json:"menu_type,omitempty"`
	Path          string                 `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`
	Component     string                 `protobuf:"bytes,6,opt,name=component,proto3" json:"component,omitempty"`
	Permission    string                 `protobuf:"bytes,7,opt,name=permission,proto3" json:"permission,omitempty"`
	Icon          string                 `protobuf:"bytes,8,opt,name=icon,proto3" json:"icon,omitempty"`
	Sort          int32                  `protobuf:"varint,9,opt,name=sort,proto3" json:"sort,omitempty"`
	Visible       int32                  `protobuf:"varint,10,opt,name=visible,proto3" json:"visible,omitempty"`
	Status        int32                  `protobuf:"varint,11,opt,name=status,proto3" json:"status,omitempty"`
	Children      []*MenuNode            `protobuf:"bytes,12,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuNode) Reset() {
	*x = MenuNode{}
	mi := &file_system_menu_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuNode) ProtoMessage() {}

func (x *MenuNode) ProtoReflect() protoreflect.Message {
	mi := &file_system_menu_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuNode.ProtoReflect.Descriptor instead.
func (*MenuNode) Descriptor() ([]byte, []int) {
	return file_system_menu_proto_rawDescGZIP(), []int{2}
}

func (x *MenuNode) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MenuNode) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *MenuNode) GetMenuName() string {
	if x != nil {
		return x.MenuName
	}
	return ""
}

func (x *MenuNode) GetMenuType() int32 {
	if x != nil {
		return x.MenuType
	}
	return 0
}

func (x *MenuNode) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *MenuNode) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *MenuNode) GetPermission() string {
	if x != nil {
		return x.Permission
	}
	return ""
}

func (x *MenuNode) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *MenuNode) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *MenuNode) GetVisible() int32 {
	if x != nil {
		return x.Visible
	}
	return 0
}

func (x *MenuNode) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *MenuNode) GetChildren() []*MenuNode {
	if x != nil {
		return x.Children
	}
	return nil
}

type MenuTreeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*MenuNode            `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuTreeResp) Reset() {
	*x = MenuTreeResp{}
	mi := &file_system_menu_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuTreeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuTreeResp) ProtoMessage() {}

func (x *MenuTreeResp) ProtoReflect() protoreflect.Message {
	mi := &file_system_menu_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuTreeResp.ProtoReflect.Descriptor instead.
func (*MenuTreeResp) Descriptor() ([]byte, []int) {
	return file_system_menu_proto_rawDescGZIP(), []int{3}
}

func (x *MenuTreeResp) GetList() []*MenuNode {
	if x != nil {
		return x.List
	}
	return nil
}

var File_system_menu_proto protoreflect.FileDescriptor

const file_system_menu_proto_rawDesc = "" +
	"\n" +
	"\x11system/menu.proto\x12\x06system\x1a\x13system/common.proto\"\x92\x02\n" +
	"\rCreateMenuReq\x12\x1b\n" +
	"\tparent_id\x18\x01 \x01(\x03R\bparentId\x12\x1b\n" +
	"\tmenu_name\x18\x02 \x01(\tR\bmenuName\x12\x1b\n" +
	"\tmenu_type\x18\x03 \x01(\x05R\bmenuType\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x1c\n" +
	"\tcomponent\x18\x05 \x01(\tR\tcomponent\x12\x1e\n" +
	"\n" +
	"permission\x18\x06 \x01(\tR\n" +
	"permission\x12\x12\n" +
	"\x04icon\x18\a \x01(\tR\x04icon\x12\x12\n" +
	"\x04sort\x18\b \x01(\x05R\x04sort\x12\x18\n" +
	"\avisible\x18\t \x01(\x05R\avisible\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\x05R\x06status\"\xa2\x02\n" +
	"\rUpdateMenuReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\x03R\bparentId\x12\x1b\n" +
	"\tmenu_name\x18\x03 \x01(\tR\bmenuName\x12\x1b\n" +
	"\tmenu_type\x18\x04 \x01(\x05R\bmenuType\x12\x12\n" +
	"\x04path\x18\x05 \x01(\tR\x04path\x12\x1c\n" +
	"\tcomponent\x18\x06 \x01(\tR\tcomponent\x12\x1e\n" +
	"\n" +
	"permission\x18\a \x01(\tR\n" +
	"permission\x12\x12\n" +
	"\x04icon\x18\b \x01(\tR\x04icon\x12\x12\n" +
	"\x04sort\x18\t \x01(\x05R\x04sort\x12\x18\n" +
	"\avisible\x18\n" +
	" \x01(\x05R\avisible\x12\x16\n" +
	"\x06status\x18\v \x01(\x05R\x06status\"\xcb\x02\n" +
	"\bMenuNode\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\x03R\bparentId\x12\x1b\n" +
	"\tmenu_name\x18\x03 \x01(\tR\bmenuName\x12\x1b\n" +
	"\tmenu_type\x18\x04 \x01(\x05R\bmenuType\x12\x12\n" +
	"\x04path\x18\x05 \x01(\tR\x04path\x12\x1c\n" +
	"\tcomponent\x18\x06 \x01(\tR\tcomponent\x12\x1e\n" +
	"\n" +
	"permission\x18\a \x01(\tR\n" +
	"permission\x12\x12\n" +
	"\x04icon\x18\b \x01(\tR\x04icon\x12\x12\n" +
	"\x04sort\x18\t \x01(\x05R\x04sort\x12\x18\n" +
	"\avisible\x18\n" +
	" \x01(\x05R\avisible\x12\x16\n" +
	"\x06status\x18\v \x01(\x05R\x06status\x12,\n" +
	"\bchildren\x18\f \x03(\v2\x10.system.MenuNodeR\bchildren\"4\n" +
	"\fMenuTreeResp\x12$\n" +
	"\x04list\x18\x01 \x03(\v2\x10.system.MenuNodeR\x04list2\xd6\x01\n" +
	"\vMenuService\x122\n" +
	"\vGetMenuTree\x12\r.system.Empty\x1a\x14.system.MenuTreeResp\x123\n" +
	"\n" +
	"CreateMenu\x12\x15.system.CreateMenuReq\x1a\x0e.system.IDResp\x122\n" +
	"\n" +
	"UpdateMenu\x12\x15.system.UpdateMenuReq\x1a\r.system.Empty\x12*\n" +
	"\n" +
	"DeleteMenu\x12\r.system.IDReq\x1a\r.system.EmptyB%Z#management-backend/api/proto/systemb\x06proto3"

var (
	file_system_menu_proto_rawDescOnce sync.Once
	file_system_menu_proto_rawDescData []byte
)

func file_system_menu_proto_rawDescGZIP() []byte {
	file_system_menu_proto_rawDescOnce.Do(func() {
		file_system_menu_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_system_menu_proto_rawDesc), len(file_system_menu_proto_rawDesc)))
	})
	return file_system_menu_proto_rawDescData
}

var file_system_menu_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_system_menu_proto_goTypes = []any{
	(*CreateMenuReq)(nil), // 0: system.CreateMenuReq
	(*UpdateMenuReq)(nil), // 1: system.UpdateMenuReq
	(*MenuNode)(nil),      // 2: system.MenuNode
	(*MenuTreeResp)(nil),  // 3: system.MenuTreeResp
	(*Empty)(nil),         // 4: system.Empty
	(*IDReq)(nil),         // 5: system.IDReq
	(*IDResp)(nil),        // 6: system.IDResp
}
var file_system_menu_proto_depIdxs = []int32{
	2, // 0: system.MenuNode.children:type_name -> system.MenuNode
	2, // 1: system.MenuTreeResp.list:type_name -> system.MenuNode
	4, // 2: system.MenuService.GetMenuTree:input_type -> system.Empty
	0, // 3: system.MenuService.CreateMenu:input_type -> system.CreateMenuReq
	1, // 4: system.MenuService.UpdateMenu:input_type -> system.UpdateMenuReq
	5, // 5: system.MenuService.DeleteMenu:input_type -> system.IDReq
	3, // 6: system.MenuService.GetMenuTree:output_type -> system.MenuTreeResp
	6, // 7: system.MenuService.CreateMenu:output_type -> system.IDResp
	4, // 8: system.MenuService.UpdateMenu:output_type -> system.Empty
	4, // 9: system.MenuService.DeleteMenu:output_type -> system.Empty
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_system_menu_proto_init() }
func file_system_menu_proto_init() {
	if File_system_menu_proto != nil {
		return
	}
	file_system_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_system_menu_proto_rawDesc), len(file_system_menu_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_system_menu_proto_goTypes,
		DependencyIndexes: file_system_menu_proto_depIdxs,
		MessageInfos:      file_system_menu_proto_msgTypes,
	}.Build()
	File_system_menu_proto = out.File
	file_system_menu_proto_goTypes = nil
	file_system_menu_proto_depIdxs = nil
}
