// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: system/role.proto

package system

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListRolesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	RoleName      string                 `protobuf:"bytes,3,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	RoleCode      string                 `protobuf:"bytes,4,opt,name=role_code,json=roleCode,proto3" json:"role_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRolesReq) Reset() {
	*x = ListRolesReq{}
	mi := &file_system_role_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolesReq) ProtoMessage() {}

func (x *ListRolesReq) ProtoReflect() protoreflect.Message {
	mi := &file_system_role_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolesReq.ProtoReflect.Descriptor instead.
func (*ListRolesReq) Descriptor() ([]byte, []int) {
	return file_system_role_proto_rawDescGZIP(), []int{0}
}

func (x *ListRolesReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListRolesReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListRolesReq) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *ListRolesReq) GetRoleCode() string {
	if x != nil {
		return x.RoleCode
	}
	return ""
}

type CreateRoleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleName      string                 `protobuf:"bytes,1,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	RoleCode      string                 `protobuf:"bytes,2,opt,name=role_code,json=roleCode,proto3" json:"role_code,omitempty"`
	DataScope     int32                  `protobuf:"varint,3,opt,name=data_scope,json=dataScope,proto3" json:"data_scope,omitempty"`
	Sort          int32                  `protobuf:"varint,4,opt,name=sort,proto3" json:"sort,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	Remark        string                 `protobuf:"bytes,6,opt,name=remark,proto3" json:"remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleReq) Reset() {
	*x = CreateRoleReq{}
	mi := &file_system_role_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleReq) ProtoMessage() {}

func (x *CreateRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_system_role_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleReq.ProtoReflect.Descriptor instead.
func (*CreateRoleReq) Descriptor() ([]byte, []int) {
	return file_system_role_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRoleReq) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *CreateRoleReq) GetRoleCode() string {
	if x != nil {
		return x.RoleCode
	}
	return ""
}

func (x *CreateRoleReq) GetDataScope() int32 {
	if x != nil {
		return x.DataScope
	}
	return 0
}

func (x *CreateRoleReq) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *CreateRoleReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CreateRoleReq) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type UpdateRoleReq struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RoleName         string                 `protobuf:"bytes,2,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	RoleCode         string                 `protobuf:"bytes,3,opt,name=role_code,json=roleCode,proto3" json:"role_code,omitempty"`
	DataScope        int32                  `protobuf:"varint,4,opt,name=data_scope,json=dataScope,proto3" json:"data_scope,omitempty"`
	DataScopeDeptIds []int64                `protobuf:"varint,5,rep,packed,name=data_scope_dept_ids,json=dataScopeDeptIds,proto3" json:"data_scope_dept_ids,omitempty"`
	Sort             int32                  `protobuf:"varint,6,opt,name=sort,proto3" json:"sort,omitempty"`
	Status           int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	Remark           string                 `protobuf:"bytes,8,opt,name=remark,proto3" json:"remark,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateRoleReq) Reset() {
	*x = UpdateRoleReq{}
	mi := &file_system_role_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleReq) ProtoMessage() {}

func (x *UpdateRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_system_role_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleReq.ProtoReflect.Descriptor instead.
func (*UpdateRoleReq) Descriptor() ([]byte, []int) {
	return file_system_role_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateRoleReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateRoleReq) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *UpdateRoleReq) GetRoleCode() string {
	if x != nil {
		return x.RoleCode
	}
	return ""
}

func (x *UpdateRoleReq) GetDataScope() int32 {
	if x != nil {
		return x.DataScope
	}
	return 0
}

func (x *UpdateRoleReq) GetDataScopeDeptIds() []int64 {
	if x != nil {
		return x.DataScopeDeptIds
	}
	return nil
}

func (x *UpdateRoleReq) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *UpdateRoleReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdateRoleReq) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type RoleResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RoleName      string                 `protobuf:"bytes,2,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	RoleCode      string                 `protobuf:"bytes,3,opt,name=role_code,json=roleCode,proto3" json:"role_code,omitempty"`
	DataScope     int32                  `protobuf:"varint,4,opt,name=data_scope,json=dataScope,proto3" json:"data_scope,omitempty"`
	Sort          int32                  `protobuf:"varint,5,opt,name=sort,proto3" json:"sort,omitempty"`
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	CreateTime    string                 `protobuf:"bytes,7,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleResp) Reset() {
	*x = RoleResp{}
	mi := &file_system_role_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleResp) ProtoMessage() {}

func (x *RoleResp) ProtoReflect() protoreflect.Message {
	mi := &file_system_role_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleResp.ProtoReflect.Descriptor instead.
func (*RoleResp) Descriptor() ([]byte, []int) {
	return file_system_role_proto_rawDescGZIP(), []int{3}
}

func (x *RoleResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoleResp) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *RoleResp) GetRoleCode() string {
	if x != nil {
		return x.RoleCode
	}
	return ""
}

func (x *RoleResp) GetDataScope() int32 {
	if x != nil {
		return x.DataScope
	}
	return 0
}

func (x *RoleResp) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *RoleResp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RoleResp) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

type RoleListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*RoleResp            `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleListResp) Reset() {
	*x = RoleListResp{}
	mi := &file_system_role_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleListResp) ProtoMessage() {}

func (x *RoleListResp) ProtoReflect() protoreflect.Message {
	mi := &file_system_role_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleListResp.ProtoReflect.Descriptor instead.
func (*RoleListResp) Descriptor() ([]byte, []int) {
	return file_system_role_proto_rawDescGZIP(), []int{4}
}

func (x *RoleListResp) GetList() []*RoleResp {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *RoleListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_system_role_proto protoreflect.FileDescriptor

const file_system_role_proto_rawDesc = "" +
	"\n" +
	"\x11system/role.proto\x12\x06system\x1a\x13system/common.proto\"y\n" +
	"\fListRolesReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1b\n" +
	"\trole_name\x18\x03 \x01(\tR\broleName\x12\x1b\n" +
	"\trole_code\x18\x04 \x01(\tR\broleCode\"\xac\x01\n" +
	"\rCreateRoleReq\x12\x1b\n" +
	"\trole_name\x18\x01 \x01(\tR\broleName\x12\x1b\n" +
	"\trole_code\x18\x02 \x01(\tR\broleCode\x12\x1d\n" +
	"\n" +
	"data_scope\x18\x03 \x01(\x05R\tdataScope\x12\x12\n" +
	"\x04sort\x18\x04 \x01(\x05R\x04sort\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12\x16\n" +
	"\x06remark\x18\x06 \x01(\tR\x06remark\"\xeb\x01\n" +
	"\rUpdateRoleReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\trole_name\x18\x02 \x01(\tR\broleName\x12\x1b\n" +
	"\trole_code\x18\x03 \x01(\tR\broleCode\x12\x1d\n" +
	"\n" +
	"data_scope\x18\x04 \x01(\x05R\tdataScope\x12-\n" +
	"\x13data_scope_dept_ids\x18\x05 \x03(\x03R\x10dataScopeDeptIds\x12\x12\n" +
	"\x04sort\x18\x06 \x01(\x05R\x04sort\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\x12\x16\n" +
	"\x06remark\x18\b \x01(\tR\x06remark\"\xc0\x01\n" +
	"\bRoleResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\trole_name\x18\x02 \x01(\tR\broleName\x12\x1b\n" +
	"\trole_code\x18\x03 \x01(\tR\broleCode\x12\x1d\n" +
	"\n" +
	"data_scope\x18\x04 \x01(\x05R\tdataScope\x12\x12\n" +
	"\x04sort\x18\x05 \x01(\x05R\x04sort\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12\x1f\n" +
	"\vcreate_time\x18\a \x01(\tR\n" +
	"createTime\"J\n" +
	"\fRoleListResp\x12$\n" +
	"\x04list\x18\x01 \x03(\v2\x10.system.RoleRespR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total2\x87\x02\n" +
	"\vRoleService\x12*\n" +
	"\aGetRole\x12\r.system.IDReq\x1a\x10.system.RoleResp\x127\n" +
	"\tListRoles\x12\x14.system.ListRolesReq\x1a\x14.system.RoleListResp\x123\n" +
	"\n" +
	"CreateRole\x12\x15.system.CreateRoleReq\x1a\x0e.system.IDResp\x122\n" +
	"\n" +
	"UpdateRole\x12\x15.system.UpdateRoleReq\x1a\r.system.Empty\x12*\n" +
	"\n" +
	"DeleteRole\x12\r.system.IDReq\x1a\r.system.EmptyB%Z#management-backend/api/proto/systemb\x06proto3"

var (
	file_system_role_proto_rawDescOnce sync.Once
	file_system_role_proto_rawDescData []byte
)

func file_system_role_proto_rawDescGZIP() []byte {
	file_system_role_proto_rawDescOnce.Do(func() {
		file_system_role_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_system_role_proto_rawDesc), len(file_system_role_proto_rawDesc)))
	})
	return file_system_role_proto_rawDescData
}

var file_system_role_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_system_role_proto_goTypes = []any{
	(*ListRolesReq)(nil),  // 0: system.ListRolesReq
	(*CreateRoleReq)(nil), // 1: system.CreateRoleReq
	(*UpdateRoleReq)(nil), // 2: system.UpdateRoleReq
	(*RoleResp)(nil),      // 3: system.RoleResp
	(*RoleListResp)(nil),  // 4: system.RoleListResp
	(*IDReq)(nil),         // 5: system.IDReq
	(*IDResp)(nil),        // 6: system.IDResp
	(*Empty)(nil),         // 7: system.Empty
}
var file_system_role_proto_depIdxs = []int32{
	3, // 0: system.RoleListResp.list:type_name -> system.RoleResp
	5, // 1: system.RoleService.GetRole:input_type -> system.IDReq
	0, // 2: system.RoleService.ListRoles:input_type -> system.ListRolesReq
	1, // 3: system.RoleService.CreateRole:input_type -> system.CreateRoleReq
	2, // 4: system.RoleService.UpdateRole:input_type -> system.UpdateRoleReq
	5, // 5: system.RoleService.DeleteRole:input_type -> system.IDReq
	3, // 6: system.RoleService.GetRole:output_type -> system.RoleResp
	4, // 7: system.RoleService.ListRoles:output_type -> system.RoleListResp
	6, // 8: system.RoleService.CreateRole:output_type -> system.IDResp
	7, // 9: system.RoleService.UpdateRole:output_type -> system.Empty
	7, // 10: system.RoleService.DeleteRole:output_type -> system.Empty
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_system_role_proto_init() }
func file_system_role_proto_init() {
	if File_system_role_proto != nil {
		return
	}
	file_system_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_system_role_proto_rawDesc), len(file_system_role_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_system_role_proto_goTypes,
		DependencyIndexes: file_system_role_proto_depIdxs,
		MessageInfos:      file_system_role_proto_msgTypes,
	}.Build()
	File_system_role_proto = out.File
	file_system_role_proto_goTypes = nil
	file_system_role_proto_depIdxs = nil
}
