// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: workflow/workflow.proto

package workflow

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateWorkflowReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CategoryId    int64                  `protobuf:"varint,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	TenantId      int64                  `protobuf:"varint,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Creator       int64                  `protobuf:"varint,4,opt,name=creator,proto3" json:"creator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWorkflowReq) Reset() {
	*x = CreateWorkflowReq{}
	mi := &file_workflow_workflow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkflowReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkflowReq) ProtoMessage() {}

func (x *CreateWorkflowReq) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_workflow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkflowReq.ProtoReflect.Descriptor instead.
func (*CreateWorkflowReq) Descriptor() ([]byte, []int) {
	return file_workflow_workflow_proto_rawDescGZIP(), []int{0}
}

func (x *CreateWorkflowReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateWorkflowReq) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *CreateWorkflowReq) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *CreateWorkflowReq) GetCreator() int64 {
	if x != nil {
		return x.Creator
	}
	return 0
}

type CreateWorkflowResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWorkflowResp) Reset() {
	*x = CreateWorkflowResp{}
	mi := &file_workflow_workflow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkflowResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkflowResp) ProtoMessage() {}

func (x *CreateWorkflowResp) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_workflow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkflowResp.ProtoReflect.Descriptor instead.
func (*CreateWorkflowResp) Descriptor() ([]byte, []int) {
	return file_workflow_workflow_proto_rawDescGZIP(), []int{1}
}

func (x *CreateWorkflowResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type WorkflowIDReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      int64                  `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowIDReq) Reset() {
	*x = WorkflowIDReq{}
	mi := &file_workflow_workflow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowIDReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowIDReq) ProtoMessage() {}

func (x *WorkflowIDReq) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_workflow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowIDReq.ProtoReflect.Descriptor instead.
func (*WorkflowIDReq) Descriptor() ([]byte, []int) {
	return file_workflow_workflow_proto_rawDescGZIP(), []int{2}
}

func (x *WorkflowIDReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WorkflowIDReq) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

type ExecuteWorkflowReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    int64                  `protobuf:"varint,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	TenantId      int64                  `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Creator       int64                  `protobuf:"varint,3,opt,name=creator,proto3" json:"creator,omitempty"`
	Variables     string                 `protobuf:"bytes,4,opt,name=variables,proto3" json:"variables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteWorkflowReq) Reset() {
	*x = ExecuteWorkflowReq{}
	mi := &file_workflow_workflow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteWorkflowReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteWorkflowReq) ProtoMessage() {}

func (x *ExecuteWorkflowReq) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_workflow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteWorkflowReq.ProtoReflect.Descriptor instead.
func (*ExecuteWorkflowReq) Descriptor() ([]byte, []int) {
	return file_workflow_workflow_proto_rawDescGZIP(), []int{3}
}

func (x *ExecuteWorkflowReq) GetWorkflowId() int64 {
	if x != nil {
		return x.WorkflowId
	}
	return 0
}

func (x *ExecuteWorkflowReq) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *ExecuteWorkflowReq) GetCreator() int64 {
	if x != nil {
		return x.Creator
	}
	return 0
}

func (x *ExecuteWorkflowReq) GetVariables() string {
	if x != nil {
		return x.Variables
	}
	return ""
}

type ExecuteWorkflowResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    int64                  `protobuf:"varint,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteWorkflowResp) Reset() {
	*x = ExecuteWorkflowResp{}
	mi := &file_workflow_workflow_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteWorkflowResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteWorkflowResp) ProtoMessage() {}

func (x *ExecuteWorkflowResp) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_workflow_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteWorkflowResp.ProtoReflect.Descriptor instead.
func (*ExecuteWorkflowResp) Descriptor() ([]byte, []int) {
	return file_workflow_workflow_proto_rawDescGZIP(), []int{4}
}

func (x *ExecuteWorkflowResp) GetInstanceId() int64 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

type GetInstanceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      int64                  `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInstanceReq) Reset() {
	*x = GetInstanceReq{}
	mi := &file_workflow_workflow_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInstanceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInstanceReq) ProtoMessage() {}

func (x *GetInstanceReq) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_workflow_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInstanceReq.ProtoReflect.Descriptor instead.
func (*GetInstanceReq) Descriptor() ([]byte, []int) {
	return file_workflow_workflow_proto_rawDescGZIP(), []int{5}
}

func (x *GetInstanceReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetInstanceReq) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

type InstanceResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	WorkflowId    int64                  `protobuf:"varint,2,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Variables     string                 `protobuf:"bytes,4,opt,name=variables,proto3" json:"variables,omitempty"`
	Result        string                 `protobuf:"bytes,5,opt,name=result,proto3" json:"result,omitempty"`
	DurationMs    int64                  `protobuf:"varint,6,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,7,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	StartedAt     string                 `protobuf:"bytes,8,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstanceResp) Reset() {
	*x = InstanceResp{}
	mi := &file_workflow_workflow_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceResp) ProtoMessage() {}

func (x *InstanceResp) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_workflow_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceResp.ProtoReflect.Descriptor instead.
func (*InstanceResp) Descriptor() ([]byte, []int) {
	return file_workflow_workflow_proto_rawDescGZIP(), []int{6}
}

func (x *InstanceResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *InstanceResp) GetWorkflowId() int64 {
	if x != nil {
		return x.WorkflowId
	}
	return 0
}

func (x *InstanceResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *InstanceResp) GetVariables() string {
	if x != nil {
		return x.Variables
	}
	return ""
}

func (x *InstanceResp) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *InstanceResp) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *InstanceResp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *InstanceResp) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_workflow_workflow_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_workflow_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_workflow_workflow_proto_rawDescGZIP(), []int{7}
}

var File_workflow_workflow_proto protoreflect.FileDescriptor

const file_workflow_workflow_proto_rawDesc = "" +
	"\n" +
	"\x17workflow/workflow.proto\x12\bworkflow\"\x7f\n" +
	"\x11CreateWorkflowReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vcategory_id\x18\x02 \x01(\x03R\n" +
	"categoryId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\x03R\btenantId\x12\x18\n" +
	"\acreator\x18\x04 \x01(\x03R\acreator\"$\n" +
	"\x12CreateWorkflowResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"<\n" +
	"\rWorkflowIDReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\x03R\btenantId\"\x8a\x01\n" +
	"\x12ExecuteWorkflowReq\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\x03R\n" +
	"workflowId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\x03R\btenantId\x12\x18\n" +
	"\acreator\x18\x03 \x01(\x03R\acreator\x12\x1c\n" +
	"\tvariables\x18\x04 \x01(\tR\tvariables\"6\n" +
	"\x13ExecuteWorkflowResp\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\x03R\n" +
	"instanceId\"=\n" +
	"\x0eGetInstanceReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\x03R\btenantId\"\xea\x01\n" +
	"\fInstanceResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vworkflow_id\x18\x02 \x01(\x03R\n" +
	"workflowId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1c\n" +
	"\tvariables\x18\x04 \x01(\tR\tvariables\x12\x16\n" +
	"\x06result\x18\x05 \x01(\tR\x06result\x12\x1f\n" +
	"\vduration_ms\x18\x06 \x01(\x03R\n" +
	"durationMs\x12\x1b\n" +
	"\terror_msg\x18\a \x01(\tR\berrorMsg\x12\x1d\n" +
	"\n" +
	"started_at\x18\b \x01(\tR\tstartedAt\"\a\n" +
	"\x05Empty2\xed\x02\n" +
	"\x0fWorkflowService\x12K\n" +
	"\x0eCreateWorkflow\x12\x1b.workflow.CreateWorkflowReq\x1a\x1c.workflow.CreateWorkflowResp\x12<\n" +
	"\x10ActivateWorkflow\x12\x17.workflow.WorkflowIDReq\x1a\x0f.workflow.Empty\x12>\n" +
	"\x12DeactivateWorkflow\x12\x17.workflow.WorkflowIDReq\x1a\x0f.workflow.Empty\x12N\n" +
	"\x0fExecuteWorkflow\x12\x1c.workflow.ExecuteWorkflowReq\x1a\x1d.workflow.ExecuteWorkflowResp\x12?\n" +
	"\vGetInstance\x12\x18.workflow.GetInstanceReq\x1a\x16.workflow.InstanceRespB'Z%management-backend/api/proto/workflowb\x06proto3"

var (
	file_workflow_workflow_proto_rawDescOnce sync.Once
	file_workflow_workflow_proto_rawDescData []byte
)

func file_workflow_workflow_proto_rawDescGZIP() []byte {
	file_workflow_workflow_proto_rawDescOnce.Do(func() {
		file_workflow_workflow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workflow_workflow_proto_rawDesc), len(file_workflow_workflow_proto_rawDesc)))
	})
	return file_workflow_workflow_proto_rawDescData
}

var file_workflow_workflow_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_workflow_workflow_proto_goTypes = []any{
	(*CreateWorkflowReq)(nil),   // 0: workflow.CreateWorkflowReq
	(*CreateWorkflowResp)(nil),  // 1: workflow.CreateWorkflowResp
	(*WorkflowIDReq)(nil),       // 2: workflow.WorkflowIDReq
	(*ExecuteWorkflowReq)(nil),  // 3: workflow.ExecuteWorkflowReq
	(*ExecuteWorkflowResp)(nil), // 4: workflow.ExecuteWorkflowResp
	(*GetInstanceReq)(nil),      // 5: workflow.GetInstanceReq
	(*InstanceResp)(nil),        // 6: workflow.InstanceResp
	(*Empty)(nil),               // 7: workflow.Empty
}
var file_workflow_workflow_proto_depIdxs = []int32{
	0, // 0: workflow.WorkflowService.CreateWorkflow:input_type -> workflow.CreateWorkflowReq
	2, // 1: workflow.WorkflowService.ActivateWorkflow:input_type -> workflow.WorkflowIDReq
	2, // 2: workflow.WorkflowService.DeactivateWorkflow:input_type -> workflow.WorkflowIDReq
	3, // 3: workflow.WorkflowService.ExecuteWorkflow:input_type -> workflow.ExecuteWorkflowReq
	5, // 4: workflow.WorkflowService.GetInstance:input_type -> workflow.GetInstanceReq
	1, // 5: workflow.WorkflowService.CreateWorkflow:output_type -> workflow.CreateWorkflowResp
	7, // 6: workflow.WorkflowService.ActivateWorkflow:output_type -> workflow.Empty
	7, // 7: workflow.WorkflowService.DeactivateWorkflow:output_type -> workflow.Empty
	4, // 8: workflow.WorkflowService.ExecuteWorkflow:output_type -> workflow.ExecuteWorkflowResp
	6, // 9: workflow.WorkflowService.GetInstance:output_type -> workflow.InstanceResp
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_workflow_workflow_proto_init() }
func file_workflow_workflow_proto_init() {
	if File_workflow_workflow_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workflow_workflow_proto_rawDesc), len(file_workflow_workflow_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_workflow_workflow_proto_goTypes,
		DependencyIndexes: file_workflow_workflow_proto_depIdxs,
		MessageInfos:      file_workflow_workflow_proto_msgTypes,
	}.Build()
	File_workflow_workflow_proto = out.File
	file_workflow_workflow_proto_goTypes = nil
	file_workflow_workflow_proto_depIdxs = nil
}
