// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: workflow/workflow.proto

package workflow

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkflowService_CreateWorkflow_FullMethodName     = "/workflow.WorkflowService/CreateWorkflow"
	WorkflowService_ActivateWorkflow_FullMethodName   = "/workflow.WorkflowService/ActivateWorkflow"
	WorkflowService_DeactivateWorkflow_FullMethodName = "/workflow.WorkflowService/DeactivateWorkflow"
	WorkflowService_ExecuteWorkflow_FullMethodName    = "/workflow.WorkflowService/ExecuteWorkflow"
	WorkflowService_GetInstance_FullMethodName        = "/workflow.WorkflowService/GetInstance"
)

// WorkflowServiceClient is the client API for WorkflowService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkflowServiceClient interface {
	// 创建工作流
	CreateWorkflow(ctx context.Context, in *CreateWorkflowReq, opts ...grpc.CallOption) (*CreateWorkflowResp, error)
	// 激活工作流
	ActivateWorkflow(ctx context.Context, in *WorkflowIDReq, opts ...grpc.CallOption) (*Empty, error)
	// 停用工作流
	DeactivateWorkflow(ctx context.Context, in *WorkflowIDReq, opts ...grpc.CallOption) (*Empty, error)
	// 执行工作流
	ExecuteWorkflow(ctx context.Context, in *ExecuteWorkflowReq, opts ...grpc.CallOption) (*ExecuteWorkflowResp, error)
	// 查询执行实例
	GetInstance(ctx context.Context, in *GetInstanceReq, opts ...grpc.CallOption) (*InstanceResp, error)
}

type workflowServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkflowServiceClient(cc grpc.ClientConnInterface) WorkflowServiceClient {
	return &workflowServiceClient{cc}
}

func (c *workflowServiceClient) CreateWorkflow(ctx context.Context, in *CreateWorkflowReq, opts ...grpc.CallOption) (*CreateWorkflowResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateWorkflowResp)
	err := c.cc.Invoke(ctx, WorkflowService_CreateWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) ActivateWorkflow(ctx context.Context, in *WorkflowIDReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, WorkflowService_ActivateWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) DeactivateWorkflow(ctx context.Context, in *WorkflowIDReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, WorkflowService_DeactivateWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) ExecuteWorkflow(ctx context.Context, in *ExecuteWorkflowReq, opts ...grpc.CallOption) (*ExecuteWorkflowResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteWorkflowResp)
	err := c.cc.Invoke(ctx, WorkflowService_ExecuteWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) GetInstance(ctx context.Context, in *GetInstanceReq, opts ...grpc.CallOption) (*InstanceResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstanceResp)
	err := c.cc.Invoke(ctx, WorkflowService_GetInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkflowServiceServer is the server API for WorkflowService service.
// All implementations must embed UnimplementedWorkflowServiceServer
// for forward compatibility.
type WorkflowServiceServer interface {
	// 创建工作流
	CreateWorkflow(context.Context, *CreateWorkflowReq) (*CreateWorkflowResp, error)
	// 激活工作流
	ActivateWorkflow(context.Context, *WorkflowIDReq) (*Empty, error)
	// 停用工作流
	DeactivateWorkflow(context.Context, *WorkflowIDReq) (*Empty, error)
	// 执行工作流
	ExecuteWorkflow(context.Context, *ExecuteWorkflowReq) (*ExecuteWorkflowResp, error)
	// 查询执行实例
	GetInstance(context.Context, *GetInstanceReq) (*InstanceResp, error)
	mustEmbedUnimplementedWorkflowServiceServer()
}

// UnimplementedWorkflowServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkflowServiceServer struct{}

func (UnimplementedWorkflowServiceServer) CreateWorkflow(context.Context, *CreateWorkflowReq) (*CreateWorkflowResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateWorkflow not implemented")
}
func (UnimplementedWorkflowServiceServer) ActivateWorkflow(context.Context, *WorkflowIDReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ActivateWorkflow not implemented")
}
func (UnimplementedWorkflowServiceServer) DeactivateWorkflow(context.Context, *WorkflowIDReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeactivateWorkflow not implemented")
}
func (UnimplementedWorkflowServiceServer) ExecuteWorkflow(context.Context, *ExecuteWorkflowReq) (*ExecuteWorkflowResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteWorkflow not implemented")
}
func (UnimplementedWorkflowServiceServer) GetInstance(context.Context, *GetInstanceReq) (*InstanceResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInstance not implemented")
}
func (UnimplementedWorkflowServiceServer) mustEmbedUnimplementedWorkflowServiceServer() {}
func (UnimplementedWorkflowServiceServer) testEmbeddedByValue()                         {}

// UnsafeWorkflowServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkflowServiceServer will
// result in compilation errors.
type UnsafeWorkflowServiceServer interface {
	mustEmbedUnimplementedWorkflowServiceServer()
}

func RegisterWorkflowServiceServer(s grpc.ServiceRegistrar, srv WorkflowServiceServer) {
	// If the following call panics, it indicates UnimplementedWorkflowServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkflowService_ServiceDesc, srv)
}

func _WorkflowService_CreateWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWorkflowReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).CreateWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_CreateWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).CreateWorkflow(ctx, req.(*CreateWorkflowReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_ActivateWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkflowIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).ActivateWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_ActivateWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).ActivateWorkflow(ctx, req.(*WorkflowIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_DeactivateWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkflowIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).DeactivateWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_DeactivateWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).DeactivateWorkflow(ctx, req.(*WorkflowIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_ExecuteWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteWorkflowReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).ExecuteWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_ExecuteWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).ExecuteWorkflow(ctx, req.(*ExecuteWorkflowReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_GetInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInstanceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).GetInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_GetInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).GetInstance(ctx, req.(*GetInstanceReq))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkflowService_ServiceDesc is the grpc.ServiceDesc for WorkflowService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkflowService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "workflow.WorkflowService",
	HandlerType: (*WorkflowServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateWorkflow",
			Handler:    _WorkflowService_CreateWorkflow_Handler,
		},
		{
			MethodName: "ActivateWorkflow",
			Handler:    _WorkflowService_ActivateWorkflow_Handler,
		},
		{
			MethodName: "DeactivateWorkflow",
			Handler:    _WorkflowService_DeactivateWorkflow_Handler,
		},
		{
			MethodName: "ExecuteWorkflow",
			Handler:    _WorkflowService_ExecuteWorkflow_Handler,
		},
		{
			MethodName: "GetInstance",
			Handler:    _WorkflowService_GetInstance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "workflow/workflow.proto",
}
